
version: "3.9"

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite
    hostname: azurite
    restart: unless-stopped
    

    environment:
      AZURITE_ACCOUNTS: "${AZURITE_ACCOUNTS}"
    
    command: >
      azurite
      --blobHost 0.0.0.0
      --queueHost 0.0.0.0
      --tableHost 0.0.0.0
      --blobPort 10000
      --queuePort 10001
      --tablePort 10002
      --location /data
      --debug /data/debug.log
      --loose
      --skipApiVersionCheck
    
    volumes:
      - ${AZURITE_DATA_PATH}:/data

    networks:
      - ${STORAGE_NETWORK}
    
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${STORAGE_NETWORK}"
      
      # Blob service
      - "traefik.http.routers.azurite-blob.rule=HostRegexp(`^[a-z0-9-]+\\.blob\\.${DOMAIN}$$`)"
      - "traefik.http.routers.azurite-blob.entrypoints=websecure"
      - "traefik.http.routers.azurite-blob.tls=true"
      - "traefik.http.routers.azurite-blob.service=azurite-blob"
      - "traefik.http.services.azurite-blob.loadbalancer.server.port=10000"
      # Queue service
      - "traefik.http.routers.azurite-queue.rule=HostRegexp(`^[a-z0-9-]+\\.queue\\.${DOMAIN}$$`)"
      - "traefik.http.routers.azurite-queue.entrypoints=websecure"
      - "traefik.http.routers.azurite-queue.tls=true"
      - "traefik.http.routers.azurite-queue.service=azurite-queue"
      - "traefik.http.services.azurite-queue.loadbalancer.server.port=10001"

      # Table service
      - "traefik.http.routers.azurite-table.rule=HostRegexp(`^[a-z0-9-]+\\.table\\.${DOMAIN}$$`)"
      - "traefik.http.routers.azurite-table.entrypoints=websecure"
      - "traefik.http.routers.azurite-table.tls=true"
      - "traefik.http.routers.azurite-table.service=azurite-table"
      - "traefik.http.services.azurite-table.loadbalancer.server.port=10002"

networks:
  ${STORAGE_NETWORK}:
    external: true
